[project]
name = "srtp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deepface>=0.0.96",
    "opencv-python>=4.11.0.86",
    "tf-keras>=2.20.1",
]
